{{- if .Values.tenants }}
{{- range .Values.tenants }}
---
apiVersion: osac.openshift.io/v1alpha1
kind: Tenant
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec: {}
{{- if $.Values.controllers.storage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vast-tenant-config-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    osac.openshift.io/tenant: {{ .name | quote }}
type: Opaque
data: {}
{{- end }}
{{- end }}
{{- end }}
